[server]
maxUploadSize = 50

[theme]
primaryColor="#E22E2E"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F0F2F6"
textColor="#262730"
font="sans serif"

[client]
showErrorDetails = true
toolbarMode = "minimal"